# Generated by Django 5.2.6 on 2025-10-11 13:40

from django.db import migrations

GENRES = [
    'Action', 'Adventure', 'Comedy', 'Drama', 'Fantasy', 'Horror',
    'Isekai', 'Magic', 'Martial Arts', 'Mecha', 'Military', 'Music',
    'Mystery', 'Psychological', 'Romance', 'School Life', 'Sci-Fi',
    'Seinen', 'Shoujo', 'Shounen', 'Slice of Life', 'Sports',
    'Supernatural', 'Tragedy', 'Vampire', 'Harem', 'Reverse Harem',
    'Game', 'Historical', 'Demons', 'Police', 'Samurai'
]

def populate_genres(apps, schema_editor):
    Genre = apps.get_model('myapp', 'Genre')
    for genre_name in GENRES:
        Genre.objects.create(name=genre_name)

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_genre_book_genres'),
    ]

    operations = [
        migrations.RunPython(populate_genres),
    ]
